### ISSUE TITLE
parse detail error

### ISSUE THREAD

**Issue by sowd** [Hiroshi-Sugimura/echonet-lite.js#4]
Hi,
When I am running my [PicoGW](https://github.com/KAIT-HEMS/PicoGW) project in Raspberry pi, the following error sometimes appear.

------
parse detail error. detail string is
'8888007700ff06820ef001e062'
TypeError: Cannot read property 'toString' of undefined
at Object.EL.toHexString (/home/pi/PicoGW/node_modules/echonet-lite/index.js:280:22)
    at Object.EL.bytesToString (/home/pi/PicoGW/node_modules/echonet-lite/index.js:305:13)
    at Object.EL.parseDetail (/home/pi/PicoGW/node_modules/echonet-lite/index.js:189:37)
    at Object.EL.parseString (/home/pi/PicoGW/node_modules/echonet-lite/index.js:240:17)
    at Object.EL.parseBytes (/home/pi/PicoGW/node_modules/echonet-lite/index.js:224:14)
    at Object.EL.returner (/home/pi/PicoGW/node_modules/echonet-lite/index.js:403:15)
    at Socket.<anonymous> (/home/pi/PicoGW/node_modules/echonet-lite/index.js:109:6)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:192:7)
    at UDP.onMessage [as onmessage] (dgram.js:546:8)

**Comment by Hiroshi-Sugimura** [comment]
たぶん直ったと思う感じです。
